project_name: fastid

builds:
  - main: ./cmd/
    id: "fastid"
    binary: fastid
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-s -w"

archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - src: './configs/fastid.yml'
        dst: '.'
        strip_parent: true

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

changelog:
  use: github
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: 'Refactor'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 20
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 30
    - title: Others
      order: 900

release:
  github:
    owner: fastid
    name: fastid

  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"

announce:
  telegram:
    enabled: true
    chat_id: -1001844494348
    message_template: 'FastID project {{.Tag}} is out!'
