project_name: fastid
before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/
    id: "fastid"
    binary: fastid
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.Version={{.Version}}"

archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - src: './configs/fastid.yml'
        dst: '.'
        strip_parent: true

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

changelog:
  use: github
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: 'Refactor'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 20
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 30
    - title: Others
      order: 999

release:
  github:
    owner: fastid
    name: tmp

  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/fastid/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "docker.io/fastid/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
#  - use: buildx
#    goos: linux
#    goarch: arm64
#    image_templates:
#      - "docker.io/fastid/tmp:{{ .Version }}-arm64"
#      - "docker.io/fastid/tmp:latest-arm64"
#    build_flag_templates:
#      - "--platform=linux/arm64"
#      - "--label=org.opencontainers.image.created={{.Date}}"
#      - "--label=org.opencontainers.image.title={{.ProjectName}}"
#      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#      - "--label=org.opencontainers.image.version={{.Version}}"
#docker_manifests:
#  # https://goreleaser.com/customization/docker_manifest/
#  - name_template: docker.io/fastid/tmp:{{ .Version }}
#    image_templates:
#      - docker.io/fastid/tmp:{{ .Version }}-amd64
#      - docker.io/fastid/tmp:{{ .Version }}-arm64v8
#      - docker.io/fastid/tmp:{{ .Version }}-armv6
#      - docker.io/fastid/tmp:{{ .Version }}-armv7
#  - name_template: 0hlov3s/{{ .ProjectName }}:latest
#    image_templates:
#      - docker.io/fastid/tmp:latest-amd64
#      - docker.io/fastid/tmp:latest-arm64v8
#      - docker.io/fastid/tmp:latest-armv6
#      - docker.io/fastid/tmp:latest-armv7
