builds:
  -
    main: ./cmd/
    id: "fastid"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: fastid
    name: tmp

  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: append
  name_template: "{{.ProjectName}} v{{.Version}}"
  extra_files:
    - glob: ./configs/fastid.yml
