builds:
  - main: ./cmd/
#  - goos:
#      - linux
#      - darwin
#  - goarch:
#      - amd64
#      - arm64

release:
  github:
    owner: fastid
    name: tmp

  draft: false
  replace_existing_draft: false
  target_commitish: '{{ .Commit }}'
  discussion_category_name: General
  prerelease: auto
  mode: append

  name_template: "{{.ProjectName}} v{{.Version}}"

