builds:
  - main: ./cmd/
#  - goos:
#      - linux
#      - darwin
#  - goarch:
#      - amd64
#      - arm64

release:
  github:
    owner: fastid
    name: fastid

  draft: true
  replace_existing_draft: true
  target_commitish: '{{ .Commit }}'
  discussion_category_name: General
  prerelease: auto
  mode: append

  header: |
    ## Some title ({{ .Date }})

    Welcome to this new release!

  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

