builds:
  -
    main: ./cmd/
    id: "fastid"
    binary: fastid
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - ./configs/fastid.yml

release:
  github:
    owner: fastid
    name: tmp

  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: append
  name_template: "{{.ProjectName}} v{{.Version}}"
  extra_files:
    - glob: ./configs/fastid.yml
