builds:
  -
    main: ./cmd/
    id: "fastid"
    binary: fastid
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - src: './configs/fastid.yml'
        dst: 'fastid.yml'

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

changelog:
  use: github
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: 'Refactor'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 20
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 30
    - title: Others
      order: 999


release:
  github:
    owner: fastid
    name: tmp

  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: append
  name_template: "{{.ProjectName}} v{{.Version}}"
