openapi: "3.0.2"
info:
  title: FastID
  version: 0.0.1
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/

paths:
  /api/v1/unseal/:
    post:
      tags:
        - Unseal
      summary: Unseal database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                secret_key:
                  type: string
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_success:
                    type: boolean
          description: "200 response"
