openapi: "3.0.2"
info:
  title: FastID
  version: 0.0.1
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/

paths:
  /:
    get:
      summary: List API versions
      responses:
        '200':
          description: 200 response
